// packages/web/src/__tests__/e2e/visualScreenshots.spec.tsx
// FB-HUD-3 visual screenshot capture across 4 Pflicht-Viewports × 4 DPRs
// (1366×768, 1440×900, 1600×900, 1920×1080 × DPR 1, 2, 3, 4).
//
// The HTML fixture (`fixtures/fb-hud3-presenter-hud.html`) is generated by
// `experiences/flower-battle/__tests__/visualExport.test.tsx` (Vitest) —
// see that file for the React markup generation. This spec reuses the
// captured HTML so the Playwright runtime does not need a JSX transformer
// or a react-i18next mock.
import { mkdirSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { expect, test } from "@playwright/test"

const __filename = fileURLToPath(import.meta.url)
const __basedir = dirname(__filename)

const FIXTURE_HTML = resolve(
  __basedir,
  "fixtures/fb-hud3-presenter-hud.html",
)

const OUTPUT_DIR = resolve(
  __basedir,
  "../../experiences/flower-battle/__tests__/visual-output/fb-hud3",
)

const VIEWPORTS = [
  { width: 1366, height: 768, label: "1366x768" },
  { width: 1440, height: 900, label: "1440x900" },
  { width: 1600, height: 900, label: "1600x900" },
  { width: 1920, height: 1080, label: "1920x1080" },
] as const

const DPRS = [1, 2, 3, 4] as const

test("fixture marker exists for screenshot capture", async () => {
  const fs = await import("node:fs")
  expect(fs.existsSync(FIXTURE_HTML)).toBe(true)
})

test.describe("flower-battle presenter hud visual captures", () => {
  for (const viewport of VIEWPORTS) {
    for (const dpr of DPRS) {
      const subjectBase = `${viewport.label.replace(/x/g, "-")}-dpr-${dpr}`

      test(`viewport ${viewport.label} @ ${dpr}x`, async ({ browser }) => {
        const context = await browser.newContext({
          viewport: {
            width: viewport.width,
            height: viewport.height,
          },
          deviceScaleFactor: dpr,
        })
        const page = await context.newPage()

        try {
          const fs = await import("node:fs")
          const html = fs.readFileSync(FIXTURE_HTML, "utf8")
          await page.setContent(html, { waitUntil: "domcontentloaded" })
          const hudLocator = page.getByTestId("flower-battle-presenter-hud")
          await expect(hudLocator).toBeVisible()

          mkdirSync(OUTPUT_DIR, { recursive: true })

          await hudLocator.screenshot({
            path: resolve(OUTPUT_DIR, subjectBase + ".png"),
          })
        } finally {
          await page.close()
          await context.close()
        }
      })
    }
  }
})
