/**
 * Style Dictionary Configuration
 * Generates CSS custom properties (--ds-*) & TypeScript Token types from design.tokens.json (W3C-DTCG format).
 */

export default {
  source: ['design.tokens.json'],
  hooks: {
    formatters: {
      'typescript/tokens': ({ dictionary }) => {
        const tokens = dictionary.allTokens
        // Unique token names formatted as CSS custom properties
        const tokenNames = Array.from(
          new Set(tokens.map((t) => `--${t.name}`))
        )
        const typeUnion = tokenNames.map((name) => `  | "${name}"`).join('\n')

        return `/**
 * Auto-generated by Style Dictionary from design.tokens.json.
 * DO NOT EDIT DIRECTLY.
 */

export type CssTokenName =
${typeUnion}

/**
 * Returns a CSS \`var(...)\` expression for a design token name in a type-safe way.
 */
export function getThemeTokenCssVar(token: CssTokenName): string {
  return \`var(\${token})\`
}
`
      }
    }
  },
  platforms: {
    typescript: {
      transformGroup: 'js',
      buildPath: 'packages/common/src/',
      files: [
        {
          destination: 'theme-tokens.generated.ts',
          format: 'typescript/tokens'
        }
      ]
    },
    css: {
      transformGroup: 'css',
      buildPath: 'build/css/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            outputReferences: true
          }
        }
      ]
    }
  }
}
