// Plausible Swiss-German first names for sim-mode bots. A static pool (no
// runtime demo-data call) so the BotManager can hand out human-looking
// usernames; it dedups against the live roster and suffixes a number when the
// pool is exhausted (more bots than names).
export const BOT_NAMES: string[] = [
  "Lena",
  "Jonas",
  "Mara",
  "Elias",
  "Noah",
  "Mia",
  "Luca",
  "Lia",
  "Nico",
  "Sina",
  "Timo",
  "Anja",
  "Robin",
  "Nora",
  "Fabio",
  "Selina",
  "Yves",
  "Jana",
  "Leon",
  "Aline",
  "Silvan",
  "Chiara",
  "Manuel",
  "Tamara",
  "Ramon",
  "Livia",
  "Joel",
  "Seraina",
  "Andrin",
  "Flavia",
  "Reto",
  "Ladina",
  "Sven",
  "Ronja",
  "Kevin",
  "Vanessa",
  "Pascal",
  "Corina",
  "Dario",
  "Melina",
]
