[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:socket]
command=node /app/socket/index.cjs
environment=NODE_ENV="production",CONFIG_PATH="/app/config",RAHOOT_SIM_MODE="%(ENV_RAHOOT_SIM_MODE)s",COMFYUI_URL="%(ENV_COMFYUI_URL)s",COMFYUI_WORKFLOW="%(ENV_COMFYUI_WORKFLOW)s",COMFYUI_IMG2IMG_WORKFLOW="%(ENV_COMFYUI_IMG2IMG_WORKFLOW)s"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
