// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AchievementConfigEntry = { enabled?: boolean, name?: string, description?: string, threshold?: number, };
