// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * S2C: ai:distractorsGenerated — AI-generated distractor answers.
 */
export type AIDistractorsGeneratedPayload = { distractors: Array<string>, };
