// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Image generation provider configuration.
 */
export type AIImageProviderConfig = { id: string, label: string, baseUrl?: string, workflow?: string, resolution?: number, };
