// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIImageProviderConfig } from "./AIImageProviderConfig";

/**
 * Image provider settings.
 */
export type AIImageSettings = { activeProvider: string, providers: Array<AIImageProviderConfig>, };
