// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Text provider extended with keyConfigured flag (sent to client).
 */
export type AIProviderPublic = { id: string, label: string, kind: string, baseUrl?: string, model: string, temperature?: number, keyConfigured: boolean, };
