// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A configured text provider (no secret — see ai-secrets server-side).
 */
export type AIProviderConfig = { id: string, label: string, kind: string, baseUrl: string | null, model: string, temperature: number | null, };
