// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AISettingsPublic } from "./AISettingsPublic";

/**
 * S2C: ai:settings — Current AI settings (public, no secrets).
 */
export type AISettingsPayload = AISettingsPublic;
