// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIImageSettings } from "./AIImageSettings";
import type { AITextSettingsPublic } from "./AITextSettingsPublic";

/**
 * Public AI settings sent to client (never carries secrets).
 */
export type AISettingsPublic = { text: AITextSettingsPublic, image: AIImageSettings, };
