// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AITestResult } from "./AITestResult";

/**
 * S2C: ai:testResult — Result of provider connectivity test.
 */
export type AITestResultPayload = AITestResult;
