// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AIProviderPublic } from "./AIProviderPublic";

/**
 * Text provider settings (public version with keyConfigured).
 */
export type AITextSettingsPublic = { activeProvider: string, providers: Array<AIProviderPublic>, };
