// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of testing provider connectivity.
 */
export type AITestResult = { ok: boolean, message: string, };
