// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimatedBackgroundConfig } from "./AnimatedBackgroundConfig";

/**
 * Animated background configs for the three display slots.
 *
 * Sent/received in: Theme.backgrounds.animated
 */
export type AnimatedBackgroundsConfig = { 
/**
 * Animated config for auth screens
 */
auth: AnimatedBackgroundConfig, 
/**
 * Animated config for manager game screen
 */
managerGame: AnimatedBackgroundConfig, 
/**
 * Animated config for player game screen
 */
playerGame: AnimatedBackgroundConfig, };
