// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Animated background type for a theme slot (auth, managerGame, playerGame).
 * "none" disables animation; "creamBackdrop" enables the cream-colored floating-icon effect.
 */
export type AnimatedBackgroundType = "none" | "creamBackdrop";
