// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimatedBackgroundType } from "./AnimatedBackgroundType";

/**
 * Per-slot animated background configuration (applied to auth, managerGame, playerGame).
 * Defaults reproduce the current look (CreamBackdrop, full speed/intensity, 12 icons).
 * This is a visual no-op until the manager UI changes it.
 *
 * Sent/received in: Theme.backgrounds.animated.*
 */
export type AnimatedBackgroundConfig = { 
/**
 * Animation style: "none" or "creamBackdrop"
 */
type: AnimatedBackgroundType, 
/**
 * Animation speed multiplier; valid range 0.25–3.0 (default 1.0)
 */
speed: number, 
/**
 * Visual opacity multiplier; valid range 0.0–1.0 (default 1.0)
 */
intensity: number, 
/**
 * Number of floating icons; valid range 0–12 (default 12)
 */
iconCount: number, 
/**
 * Hex color tint for backdrop; empty string "" means use theme-derived color
 */
color: string, };
