// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Spring-physics animation config for motion transitions.
 * Defaults mirror presets.ts SPRING (stiffness=300, damping=24) and scale 1.0
 * so an absent/old theme.json stays a visual no-op.
 *
 * Sent/received in: Theme.animation
 */
export type AnimationConfig = { 
/**
 * Spring stiffness (determines snappiness); valid range 50–1000 (default 300)
 */
springStiffness: number, 
/**
 * Spring damping (reduces oscillation); valid range 5–60 (default 24)
 */
springDamping: number, 
/**
 * Global duration scale for animations; valid range 0.25–3.0 (default 1.0)
 */
durationScale: number, 
/**
 * Stagger delay scale for sequential animations; valid range 0.0–3.0 (default 1.0)
 */
staggerScale: number, };
