// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnswerAckReason } from "./AnswerAckReason";

/**
 * Answer ack payload (low-latency mode).
 * Emitted on `player:answerAck`.
 */
export type AnswerAck = { accepted: boolean, reason: AnswerAckReason, serverReceivedAtMs: bigint, clientMessageId: string | null, };
