// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reason for answer acceptance/rejection (low-latency mode).
 */
export type AnswerAckReason = "ok" | "duplicate" | "too_late" | "invalid_question" | "invalid_answer";
