// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for manager:uploadBackground and manager:backgroundUploaded events.
 * slot: one of "auth", "managerGame", "playerGame", or "logo" (ThemeSlot).
 * dataUrl: base64-encoded image data (on upload request).
 * path: server-side path to the uploaded asset (in success response).
 *
 * Sent/received in: manager:uploadBackground, manager:backgroundUploaded
 */
export type BackgroundUploadPayload = { 
/**
 * Background slot: "auth", "managerGame", "playerGame", or "logo"
 */
slot: string, 
/**
 * Base64-encoded image data (on upload request only)
 */
dataUrl?: string, 
/**
 * Server asset path (in success response only)
 */
path?: string, };
