// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogSource } from "./CatalogSource";
import type { Question } from "./Question";

/**
 * A reusable question in the catalog
 */
export type CatalogEntry = { id: string, question: Question, tags?: Array<string>, source?: CatalogSource, addedAt: string, };
