// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chase meter for DeepSeaEscape. No extra fields.
 */
export type ChaseState = { distance: number, level: number, levelCount: number, correctRatio: number, };
