// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * clock:ping payload (C2S) — client monotonic timestamp
 */
export type ClockPing = { clientSendMonoMs: bigint, };
