// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Clock sync pong response.
 * Emitted on `clock:pong`.
 */
export type ClockPong = { clientSendMonoMs: bigint, serverNowMs: bigint, };
