// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Marker for the built-in "connect" event (no payload).
 */
export type ConnectPayload = Record<string, never>;
