// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectedModes } from "./SelectedModes";

/**
 * Game creation payload with optional mode selection
 */
export type CreateGamePayload = { quizzId: string, selectedModes?: SelectedModes, 
/**
 * Class bound to this game when klassen mode is on (A10 / Wave-1 §B).
 */
classId?: bigint, };
