// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectedModes } from "./SelectedModes";

/**
 * Game creation payload with optional mode selection
 */
export type CreateGamePayload = { quizzId: string, selectedModes?: SelectedModes, };
