// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for DISPLAY.REGISTER (C2S): display registers with server.
 * Optional: the client may send `{name: "..."}`or `null`/undefined.
 * Serde defaults missing fields to None.
 */
export type DisplayRegisterPayload = { name: string | null, };
