// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayStatus } from "./DisplayStatus";

/**
 * Payload for DISPLAY.STATUS (S2C): complete display status for a game.
 * Array of connected displays with their IDs, names, and last-ping timestamps.
 */
export type DisplayStatusPayload = { displays: Array<DisplayStatus>, };
