// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for DISPLAY.REGISTERED (S2C): server confirms registration.
 * Carries the generated pairing code.
 */
export type DisplayRegisteredPayload = { code: string, };
