// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for DISPLAY.PAIR_SUCCESS (S2C): pairing confirmed.
 * Both display and manager sockets receive this confirmation.
 */
export type DisplayPairSuccessPayload = { gameId: string, };
