// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for DISPLAY.PAIR (C2S): manager pairs a display to a game.
 * The display (registered via code) is joined to the game room.
 */
export type DisplayPairPayload = { code: string, 
/**
 * Legacy fallback (socket auth is primary).
 */
managerPassword?: string, gameId: string, };
