// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for DISPLAY.DISCONNECT (C2S): display unpairs from pairing code.
 */
export type DisplayDisconnectPayload = { code: string, };
