// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * C2S: manager:editImage — Request image editing from a base image.
 */
export type EditImagePayload = { baseUrl: string, prompt: string, };
