// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * End-screen display mode (mutually exclusive)
 */
export type EndScreen = "full" | "top3" | "private";
