// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeepSeaPayload } from "./DeepSeaPayload";
import type { FlowerBattlePayload } from "./FlowerBattlePayload";
import type { PyramidPayload } from "./PyramidPayload";

/**
 * Mode-specific payload body. Tagged union: `{ mode, data }`.
 * Classic remains a unit arm; FlowerBattle carries [`FlowerBattlePayload`].
 */
export type ExperiencePayload = { "mode": "classic" } | { "mode": "pyramid", "data": PyramidPayload } | { "mode": "deepSea", "data": DeepSeaPayload } | { "mode": "flowerBattle", "data": FlowerBattlePayload };
