// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExperienceMode } from "./ExperienceMode";
import type { ExperiencePayload } from "./ExperiencePayload";
import type { ExperiencePhase } from "./ExperiencePhase";

/**
 * S2C envelope for `game:experience` transitions.
 *
 * Five structural fields + mode-tagged `payload`. No free-text / media / solution
 * fields — anti-cheat and separation from `game:status`.
 */
export type ExperienceTransition = { mode: ExperienceMode, phase: ExperiencePhase, phaseStartedAtServerMs: bigint, phaseDurationMs?: bigint, revision: number, payload: ExperiencePayload, };
