// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeepSeaPayload } from "./DeepSeaPayload";
import type { PyramidPayload } from "./PyramidPayload";

/**
 * Mode-specific payload body. Tagged union: `{ mode, data }`.
 * Classic and FlowerBattle are unit arms (FlowerBattle body → WP #927).
 */
export type ExperiencePayload = { "mode": "classic" } | { "mode": "pyramid", "data": PyramidPayload } | { "mode": "deepSea", "data": DeepSeaPayload } | { "mode": "flowerBattle" };
