// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Experience presentation mode (mutually exclusive). Exactly four values (WP #876).
 */
export type ExperienceMode = "classic" | "pyramidClimb" | "deepSeaEscape" | "flowerBattle";
