// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Experience-mode phase within a live game (exactly 8 values).
 */
export type ExperiencePhase = "intro" | "question" | "answers_locked" | "resolution" | "world_transition" | "level_complete" | "game_complete" | "game_failed";
