// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndScreen } from "./EndScreen";
import type { Player } from "./Player";
import type { TeamStanding } from "./TeamStanding";

export type FinishedData = { subject: string, top: Array<Player>, rank?: number, teamStandings?: Array<TeamStanding>, recap?: any, autoMode?: boolean, endScreen?: EndScreen, };
