// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Active temporary effect on a FlowerBattle team.
 */
export type FlowerBattleEffect = "sunbeam" | "umbrella_shield" | "acid_rain";
