// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowerBattleState } from "./FlowerBattleState";

/**
 * FlowerBattle payload body inside [`ExperiencePayload`].
 */
export type FlowerBattlePayload = { state: FlowerBattleState, };
