// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Active temporary status effect on a FlowerBattle team (WP #932).
 *
 * Fertilizer is **not** a status — it is applied instantly (+2 growth) and never
 * stored here. Wire shape is internally tagged (`kind` + camelCase fields).
 */
export type FlowerBattleEffect = { "kind": "sunbeam", expiresAfterQuestionId: number, } | { "kind": "umbrella_shield", remainingQuestions: number, } | { "kind": "acid_rain", sourceTeamId: string, expiresAfterQuestionId: number, };
