// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowerBattleEffect } from "./FlowerBattleEffect";

/**
 * Per-team public battle state (no solution / Q&A content).
 */
export type FlowerBattleTeamState = { name: string, 
/**
 * Member player UUIDs.
 */
members: Array<string>, hp: number, shield: number, effects: Array<FlowerBattleEffect>, 
/**
 * Accumulated sun points for power-up triggers (WP #930).
 */
sunPoints: number, 
/**
 * Last team that successfully acid_rain-attacked this team (WP #931).
 * Used to block back-to-back attacks from the same attacker team.
 * `None` when never attacked (or after any reset policy lands later).
 */
previousAttackerTeamId?: string, };
