// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * S2C `game:flowerBattle:gameCompleted`.
 */
export type FlowerBattleCompleted = { gameId: string, winnerTeamIds: Array<string>, };
