// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * FlowerBattle intra-mode phase (SDD §11 — 10 unit variants).
 * Distinct from [`ExperiencePhase`]; rides inside `FlowerBattleState`, not as a
 * second top-level envelope state machine.
 */
export type FlowerBattlePhase = "start" | "greeting" | "role_assignment" | "preparation" | "round1" | "round2" | "round3" | "voting" | "results" | "end";
