// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowerBattleEffect } from "./FlowerBattleEffect";

/**
 * Per-team public battle state (no solution / Q&A content).
 */
export type FlowerBattleTeamState = { name: string, 
/**
 * Member player UUIDs.
 */
members: Array<string>, hp: number, shield: number, effects: Array<FlowerBattleEffect>, 
/**
 * Accumulated sun points for power-up triggers (WP #930).
 */
sunPoints: number, };
