// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowerBattleBackground } from "./FlowerBattleBackground";
import type { FlowerBattlePhase } from "./FlowerBattlePhase";
import type { FlowerBattleTeamState } from "./FlowerBattleTeamState";
import type { PowerupOffer } from "./PowerupOffer";

/**
 * Full FlowerBattle mode state snapshot body.
 */
export type FlowerBattleState = { phase: FlowerBattlePhase, teams: Array<FlowerBattleTeamState>, background: FlowerBattleBackground, powerups: Array<PowerupOffer>, };
