// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowerBattleEffect } from "./FlowerBattleEffect";

/**
 * Personalized FlowerBattle state for one player.
 *
 * Emitted only to the player's current socket on
 * `game:flowerBattle:playerStatus`. Team assignment and all battle values are
 * server-authoritative; clients must not infer a team from the public snapshot.
 */
export type FlowerBattlePlayerStatus = { gameId: string, questionIndex: number, teamId: string | null, growthStage: number, maxGrowthStage: number, sunPoints: number, activeEffects: Array<FlowerBattleEffect>, victoryResolved: boolean, winnerTeamIds: Array<string>, isWinner: boolean, };
