// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deterministic garden-background seed + fixed recipe version.
 */
export type FlowerBattleBackground = { seed: string, 
/**
 * Always [`FLOWER_BATTLE_RECIPE_VERSION`] (`1`).
 */
recipeVersion: number, };
