// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Color palette for footer area (background and text).
 * Used for result screen and other footer elements.
 *
 * Sent/received in: Theme.footerColors
 */
export type FooterColors = { 
/**
 * Hex color for footer background
 */
bg: string, 
/**
 * Hex color for footer text
 */
text: string, };
