// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * game:successJoin payload (S2C) — mirrors node's player-manager.ts join():
 * `socket.emit(EVENTS.GAME.SUCCESS_JOIN, { gameId, playerToken })`. Was
 * previously a bare-string alias; the client (Username.tsx) reads
 * `payload.gameId` / `payload.playerToken` off an OBJECT, so a bare string
 * left both undefined — the player landed on `/party/undefined`.
 */
export type GameSuccessJoin = { gameId: string, playerToken?: string, };
