// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FinishedData } from "./FinishedData";
import type { PausedData } from "./PausedData";
import type { SelectAnswerData } from "./SelectAnswerData";
import type { ShowLeaderboardData } from "./ShowLeaderboardData";
import type { ShowPreparedData } from "./ShowPreparedData";
import type { ShowQuestionData } from "./ShowQuestionData";
import type { ShowResponsesData } from "./ShowResponsesData";
import type { ShowResultData } from "./ShowResultData";
import type { ShowRoomData } from "./ShowRoomData";
import type { ShowRoundRecapData } from "./ShowRoundRecapData";
import type { ShowStartData } from "./ShowStartData";
import type { WaitData } from "./WaitData";

/**
 * GameStatus discriminated union: status name + data
 */
export type GameStatus = { "name": "SHOW_ROOM", "data": ShowRoomData } | { "name": "SHOW_START", "data": ShowStartData } | { "name": "SHOW_PREPARED", "data": ShowPreparedData } | { "name": "SHOW_QUESTION", "data": ShowQuestionData } | { "name": "SELECT_ANSWER", "data": SelectAnswerData } | { "name": "SHOW_RESULT", "data": ShowResultData } | { "name": "SHOW_RESPONSES", "data": ShowResponsesData } | { "name": "SHOW_ROUND_RECAP", "data": ShowRoundRecapData } | { "name": "SHOW_LEADERBOARD", "data": ShowLeaderboardData } | { "name": "FINISHED", "data": FinishedData } | { "name": "WAIT", "data": WaitData } | { "name": "PAUSED", "data": PausedData };
