// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * game:startCooldown payload (S2C) — no data
 */
export type GameStartCooldown = Record<string, never>;
