// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * game:successRoom payload (S2C)
 */
export type GameSuccessRoom = { gameId: string, requireIdentifier: boolean | null, };
