// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * game:updateQuestion payload (S2C)
 */
export type GameUpdateQuestion = { current: number, total: number, };
