// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RosterEntry } from "./RosterEntry";

/**
 * game:successRoom payload (S2C)
 */
export type GameSuccessRoom = { gameId: string, requireIdentifier?: boolean, 
/**
 * True when this game is class-mode (class_id is set). Omitted for free-join.
 */
klassen?: boolean, 
/**
 * Class roster (post game-PIN join only — A8). Never includes PINs.
 */
roster?: Array<RosterEntry>, };
