// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameSummary = { gameId: string, inviteCode: string, subject: string, playerCount: number, started: boolean, managerConnected: boolean, createdAt: bigint, };
