// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Player rank entry in game results.
 * Emitted via RESULTS.DATA and RESULTS.SHARED_DATA.
 */
export type GameResultPlayer = { username: string, points: number, rank: number, };
