// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * C2S: manager:generateImage — Request image generation.
 */
export type GenerateImagePayload = { prompt: string, };
