// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Details of the hardest question (lowest correct %) in a quiz.
 */
export type HardestQuestion = { questionIndex: number, correctPct: number, };
