// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Drop-pin hotspot rectangle in relative [0–1] image space.
 */
export type Hotspot = { x: number, y: number, w: number, h: number, };
