// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A global label (Fach) defined by admin — orthogonal to subject titles, can tag quizzes/media/catalog.
 */
export type Label = { id: bigint, name: string, color: string, };
