// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HardestQuestion } from "./HardestQuestion";
import type { Superlative } from "./Superlative";

/**
 * Post-game recap with superlatives and hardest question detail.
 * Optional field on GameResult and SharedResult (RESULTS.DATA, RESULTS.SHARED_DATA).
 */
export type ManagerRecap = { superlatives: Array<Superlative>, hardestQuestion: HardestQuestion | null, };
