// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmissionCategory } from "./SubmissionCategory";

export type ManagerRejectSubmission = { id: string, reason?: string, category?: SubmissionCategory, };
