// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScoringMode } from "./ScoringMode";

export type ManagerSetGameConfig = { teamMode: boolean | null, lowLatencyEnabled: boolean | null, joinLocked: boolean | null, randomizeAnswers: boolean | null, scoringMode: ScoringMode | null, };
