// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Matching play-time row (no correctIndex — anti-cheat).
 */
export type MatchItemPlay = { label: string, options: Array<string>, };
