// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Matching left-item row: label + dropdown options + correct option index.
 */
export type MatchingItem = { label: string, options: Array<string>, correctIndex: number, };
