// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single media-library item tracked in config/media-manifest.json and shown
 * in the manager Media tab. `url` is same-origin relative (/media/<cat>/<file>).
 * Corresponds to wire events: media:data (array).
 */
export type MediaMeta = { id: string, filename: string, url: string, size: number, type: string, category: string, source: string, uploadedAt: string, width: number | null, height: number | null, };
