// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaMeta } from "./MediaMeta";

/**
 * S2C: media:data — List of all media items.
 */
export type MediaDataPayload = Array<MediaMeta>;
