// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A record of where a media item is used: quiz ID, quiz title, question index, and question label.
 * Part of MediaMeta.usage field (optional, populated server-side).
 */
export type MediaUsageEntry = { quizId: string, quizTitle: string, questionIndex: number, questionLabel: string, };
