// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * C2S: media:delete — Delete a media item by ID.
 */
export type MediaDeletePayload = { id: string, };
