// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * S2C: media:uploadSuccess — Confirmation of successful upload (no payload).
 */
export type MediaUploadSuccessPayload = null;
