// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generic wrapper for gameId + data payload
 */
export type MessageWithoutStatus<T> = { gameId: string | null, data: T, };
