// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricPercentiles } from "./MetricPercentiles";

/**
 * Metrics health snapshot (server->host).
 * Emitted on `metrics:health`.
 */
export type MetricsHealthSnapshot = { rtt: MetricPercentiles, clockOffset: MetricPercentiles, answerAck: MetricPercentiles, reconnectCount: number, rejected: { [key in string]?: number }, };
