// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metric percentiles (one bucket of rolling samples).
 */
export type MetricPercentiles = { p50: number | null, p95: number | null, count: number, };
