// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricKind } from "./MetricKind";

/**
 * Metrics sample report (client->server).
 * Sent on `metrics:report`.
 */
export type MetricsReport = { kind: MetricKind, value: number, };
