// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metrics subscription (client->server).
 * Sent on `metrics:subscribe`.
 */
export type MetricsSubscribe = { gameId?: string, };
