// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metric kind enum.
 */
export type MetricKind = "rtt" | "clockOffset" | "answerAck";
