// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * WP-H gap 1: one player's own end-of-game recap card. Node parity:
 * game-recap.ts's `PlayerRecap["myRecap"]`.
 */
export type MyRecap = { rank: number, accuracyPct: number, correct: number, wrong: number, fastestMs: number | null, peakStreak: number, achievements: Array<string>, };
