// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * player:selectedAnswer payload (C2S)
 */
export type PlayerSelectedAnswer = { answerKey: number, answerKeys?: Array<number>, answerText?: string, clientMessageId?: string, };
