// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowerBattlePlayerStatus } from "./FlowerBattlePlayerStatus";
import type { GameUpdateQuestion } from "./GameUpdateQuestion";
import type { PlayerReconnectInfo } from "./PlayerReconnectInfo";

/**
 * Player reconnect payload emitted on `player:successReconnect`.
 *
 * `flower_battle_player_status` is present only for FlowerBattle games and is
 * built from live game state + the reconnecting player's own team (never a
 * guessed/first-map team). Absent for other experience modes.
 */
export type PlayerSuccessReconnect = { gameId: string, status: any, player: PlayerReconnectInfo, currentQuestion: GameUpdateQuestion, alreadyAnswered?: boolean, flowerBattlePlayerStatus?: FlowerBattlePlayerStatus, };
