// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * player:login payload (C2S)
 */
export type PlayerLogin = { username: string, avatar?: string, identifier?: string, };
