// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-answer record for a single player on a single question.
 * Part of QuestionResult; tracked during gameplay.
 */
export type PlayerAnswerRecord = { playerName: string, 
/**
 * Single-choice answer index, or null for no answer / type-answer.
 */
answerId: number | null, 
/**
 * Multiple-select indices (absent for single-choice).
 */
answerIds?: Array<number>, 
/**
 * Free-text answer (absent for single/multiple-choice).
 */
answerText?: string, 
/**
 * Milliseconds from question start to answer, or null for legacy results.
 */
responseMs?: number, };
