// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowerBattlePlayerStatus } from "./FlowerBattlePlayerStatus";
import type { GameUpdateQuestion } from "./GameUpdateQuestion";
import type { PlayerReconnectInfo } from "./PlayerReconnectInfo";

/**
 * Player reconnect payload emitted on `player:successReconnect`.
 *
 * FlowerBattle status is optional for backward compatibility and absent until
 * reconnect-specific lifecycle wiring supplies it.
 */
export type PlayerSuccessReconnect = { gameId: string, status: any, player: PlayerReconnectInfo, currentQuestion: GameUpdateQuestion, alreadyAnswered?: boolean, flowerBattlePlayerStatus?: FlowerBattlePlayerStatus, };
