// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * player:reconnect payload (C2S)
 */
export type PlayerReconnect = { gameId: string, lastServerSeq?: number, };
