// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Player type: core game participant data.
 */
export type Player = { id: string, clientId: string, connected: boolean, username: string, points: number, streak: number, isBot: boolean | null, avatar: string | null, achievements: Array<string> | null, teamId: string | null, identifierHash: string | null, };
