// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Minimal player info in reconnect.
 */
export type PlayerReconnectInfo = { username: string, points: number, };
