// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PyramidConfidenceLevel } from "./PyramidConfidenceLevel";

/**
 * C2S payload for `player:selectConfidence`.
 */
export type PlayerSelectConfidence = { gameId: string, confidence: PyramidConfidenceLevel, };
