// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameUpdateQuestion } from "./GameUpdateQuestion";
import type { PlayerReconnectInfo } from "./PlayerReconnectInfo";

/**
 * Player reconnect payload.
 * Emitted on `player:successReconnect`.
 */
export type PlayerSuccessReconnect = { gameId: string, status: any, player: PlayerReconnectInfo, currentQuestion: GameUpdateQuestion, alreadyAnswered?: boolean, };
