// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MyRecap } from "./MyRecap";
import type { RecapHighlight } from "./RecapHighlight";

/**
 * Per-player post-game recap (WP-H gap 1): sent on FINISHED to each player
 * INSTEAD OF ManagerRecap. Node parity: game-recap.ts's `PlayerRecap`.
 */
export type PlayerRecap = { myRecap: MyRecap, highlight?: RecapHighlight, };
