// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Player } from "./Player";

/**
 * Leaderboard update payload.
 * Emitted on `player:updateLeaderboard`.
 */
export type PlayerUpdateLeaderboard = { leaderboard: Array<Player>, };
