// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * S2C `game:flowerBattle:powerupSelected`.
 */
export type PowerupSelected = { gameId: string, teamId: string, offerId: string,
/**
 * Index into the active offer option list.
 */
optionIndex: number, optionId: string,
/**
 * Server epoch ms — anchors client-side target-vote window.
 */
selectedAtServerMs: number, };
