// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PowerupOffer } from "./PowerupOffer";

/**
 * S2C `game:flowerBattle:powerupOffered`.
 */
export type PowerupOffered = { gameId: string, teamId: string, offer: PowerupOffer, };
