// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * C2S payload for `player:flowerBattle:submitPowerupVote`.
 *
 * `player_token` is **required** on the wire (SEC-01): server matches it against
 * the stored token for the socket's clientId before recording the vote.
 */
export type PowerupVotePayload = { gameId: string, 
/**
 * Index into the active offer option list.
 */
optionIndex: number, 
/**
 * Server-minted per-player secret from `game:successJoin` / localStorage.
 */
playerToken: string, };
