// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PowerupAppliedResult } from "./PowerupAppliedResult";

/**
 * S2C `game:flowerBattle:powerupApplied`.
 */
export type PowerupApplied = { gameId: string, sourceTeamId: string, optionId: string, targetTeamId?: string, applied: PowerupAppliedResult, };
