// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * S2C `game:flowerBattle:powerupSelected`.
 */
export type PowerupSelected = { gameId: string, teamId: string, offerId: string, optionIndex: number, optionId: string, selectedAtServerMs: number, };
