// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowerBattleEffect } from "./FlowerBattleEffect";

/**
 * Stable wire shape for the power-up application result.
 *
 * Protocol-local (not engine `AppliedEffect`) so clients get a typed tagged
 * union without pulling engine into the protocol crate.
 */
export type PowerupAppliedResult = { "kind": "fertilizer", growthStage: number, } | { "kind": "status", teamId: string, effect: FlowerBattleEffect, } | { "kind": "restored_idempotent" };
