// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Offered power-up choice during a FlowerBattle session.
 * `offer_type` is a free string on the contract surface (typed enum later).
 */
export type PowerupOffer = { id: string, offerType: string, 
/**
 * Expiry as server epoch ms (same convention as `phaseStartedAtServerMs`).
 */
expiresAt: bigint, };
