// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * S2C: manager:promptEnhanced — Prompt enhancement succeeded.
 */
export type PromptEnhancedPayload = { prompt: string, };
