// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TeamStep } from "./TeamStep";

/**
 * PyramidClimb payload body.
 */
export type PyramidPayload = { teamSteps: Array<TeamStep>, };
