// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional pyramid confidence vote after the regular answer (ShowResult window).
 * Distinct from the exclusive `confidence` question type (`ConfidenceLevel` in TS).
 */
export type PyramidConfidenceLevel = "low" | "medium" | "high";
