// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hotspot } from "./Hotspot";
import type { MatchingItem } from "./MatchingItem";
import type { QuestionMedia } from "./QuestionMedia";
import type { QuestionType } from "./QuestionType";
import type { SequencingItem } from "./SequencingItem";
import type { Slot } from "./Slot";

/**
 * A single question in a quiz
 */
export type Question = { question: string, type?: QuestionType, media?: QuestionMedia, answers?: Array<string>, solutions?: Array<number>, min?: number, max?: number, correct?: number, step?: number, unit?: string, chunks?: Array<string>, cooldown: number, time: number, practice?: boolean, bonus?: boolean, submittedBy?: string, acceptedAnswers?: Array<string>, matchMode?: string, tolerance?: number, decimals?: number, sentence?: string, tokens?: Array<string>, posSet?: Array<string>, disabledTokens?: Array<number>, items?: Array<SequencingItem>, correctOrder?: Array<string>, 
/**
 * Fill-blank: text segments around slots (len == slots.len() + 1).
 */
segments?: Array<string>, 
/**
 * Fill-blank: per-slot options + correctIndex.
 */
slots?: Array<Slot>, 
/**
 * Matching: left labels with dropdown options.
 */
leftItems?: Array<MatchingItem>, }, hotspots?: Array<Hotspot>, };
