// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Question type enum
 */
export type QuestionType = "choice" | "boolean" | "slider" | "poll" | "multiple-select" | "type-answer" | "sentence-builder" | "mathematik" | "wortarten" | "sequencing" | "fill-blank" | "matching" | "drop-pin" | "word-cloud" | "brainstorm" | "confidence" | "micro-lesson";
