// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Question media — image/video/audio attached to a question.
 */
export type QuestionMedia = { type: string | null, url: string, };
