// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionMedia } from "./QuestionMedia";
import type { QuestionType } from "./QuestionType";

/**
 * A single question in a quiz
 */
export type Question = { question: string, type: QuestionType | null, media: QuestionMedia | null, answers: Array<string> | null, solutions: Array<number> | null, min: number | null, max: number | null, correct: number | null, step: number | null, unit: string | null, chunks: Array<string> | null, cooldown: number, time: number, practice: boolean | null, bonus: boolean | null, submittedBy: string | null, acceptedAnswers: Array<string> | null, matchMode: string | null, };
