// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionMedia } from "./QuestionMedia";
import type { QuestionType } from "./QuestionType";

/**
 * A single question in a quiz
 */
export type Question = { question: string, type?: QuestionType, media?: QuestionMedia, answers?: Array<string>, solutions?: Array<number>, min?: number, max?: number, correct?: number, step?: number, unit?: string, chunks?: Array<string>, cooldown: number, time: number, practice?: boolean, bonus?: boolean, submittedBy?: string, acceptedAnswers?: Array<string>, matchMode?: string, tolerance?: number, decimals?: number, sentence?: string, tokens?: Array<string>, posSet?: Array<string>, };
