// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * quizz:updateSuccess response
 */
export type QuizzUpdateSuccessPayload = { id: string, };
