// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Question } from "./Question";

/**
 * A complete quiz definition
 */
export type Quizz = { subject: string, questions: Array<Question>, archived?: boolean, themeId?: string, };
