// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Question } from "./Question";

/**
 * A quiz with its server-assigned ID
 */
export type QuizzWithId = { id: string, subject: string, questions: Array<Question>, archived: boolean | null, themeId: string | null, };
