// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Color palette for rank change feedback (up/down).
 * Used when a player's rank moves up or down on the leaderboard.
 *
 * Sent/received in: Theme.rankColors
 */
export type RankColors = { 
/**
 * Hex color for rank improvement (moved up)
 */
up: string, 
/**
 * Hex color for rank decline (moved down)
 */
down: string, };
