// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuperlativeKey } from "./SuperlativeKey";

/**
 * The single superlative a player won, for the phone's 1-card highlight.
 * Node parity: game-recap.ts's `PlayerRecap["highlight"]`.
 */
export type RecapHighlight = { key: SuperlativeKey, value: number, };
