// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for themeRevision:restore request.
 * id: the revision ID to restore.
 *
 * Sent/received in: themeRevision:restore
 */
export type RestoreRevisionPayload = { 
/**
 * Revision ID to restore
 */
id: string, };
