// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Roster row returned in `game:successRoom` for klassen games (A5).
 * Never carries PINs or extra PII.
 */
export type RosterEntry = { studentId: bigint, displayName: string, alreadyJoined: boolean, };
