// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RoundRecapKey = "fastest_finger" | "first_correct" | "streak" | "highest_round_score" | "rank_climber" | "achievement_unlock" | "slowest_player" | "most_wrong";
