// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoundRecapKey } from "./RoundRecapKey";

/**
 * RoundRecapAward for per-round highlights
 */
export type RoundRecapAward = { key: RoundRecapKey, winnerName: string, winnerAvatar?: string, value?: number, };
