// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionMedia } from "./QuestionMedia";
import type { SequencingItem } from "./SequencingItem";

export type SelectAnswerData = { question: string, answers?: Array<string>, media?: QuestionMedia, time: number, totalPlayer: number, type?: string, min?: number, max?: number, step?: number, unit?: string, shuffledChunks?: Array<string>, shuffledItems?: Array<SequencingItem>, serverSeq?: number, serverNowMs?: bigint, questionStartAtServerMs?: bigint, answerDeadlineAtServerMs?: bigint, submittedBy?: string, sentence?: string, tokens?: Array<string>, posSet?: Array<string>, disabledTokens?: Array<number>, };
