// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndScreen } from "./EndScreen";

/**
 * Per-game mode selection snapshot (host's choices at game creation)
 */
export type SelectedModes = { scoringMode?: string, teamMode?: boolean, klassen?: boolean, endScreen?: EndScreen, };
