// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionMedia } from "./QuestionMedia";

export type SelectAnswerData = { question: string, answers: Array<string> | null, media: QuestionMedia | null, time: number, totalPlayer: number, type: string | null, min: number | null, max: number | null, step: number | null, unit: string | null, shuffledChunks: Array<string> | null, serverSeq: number | null, serverNowMs: bigint | null, questionStartAtServerMs: bigint | null, answerDeadlineAtServerMs: bigint | null, submittedBy: string | null, };
