// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndScreen } from "./EndScreen";
import type { ExperienceMode } from "./ExperienceMode";
import type { TeamAssignment } from "./TeamAssignment";

/**
 * Per-game mode selection snapshot (host's choices at game creation)
 */
export type SelectedModes = { scoringMode?: string, teamMode?: boolean, klassen?: boolean, endScreen?: EndScreen, 
/**
 * Per-game participant cap. None or 0 = unlimited (up to server ceiling of 200).
 * Validated and clamped server-side via resolve_player_cap().
 */
participantCap?: bigint, 
/**
 * Experience presentation mode (WP #876). None = classic default on server.
 */
experienceMode?: ExperienceMode, 
/**
 * Team assignment mode (WP #952). Default `self` — players pick; `auto` assigns
 * each joiner to the smallest team (TEAMS order as tie-break).
 */
teamAssignment: TeamAssignment, };
