// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sequencing question item with id and label
 */
export type SequencingItem = { id: string, label: string, };
