// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for manager:setSkeletonAsset and manager:setSkeletonAssetSuccess events.
 * kind: "css" or "js" — which skeleton file is being set/confirmed.
 * content: the full file text (on request); omitted in success response.
 *
 * Sent/received in: manager:setSkeletonAsset, manager:setSkeletonAssetSuccess
 */
export type SetSkeletonAssetPayload = { 
/**
 * Type of asset: "css" or "js"
 */
kind: string, 
/**
 * File content (only on set request, omitted in success response)
 */
content: string | null, };
