// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Player } from "./Player";
import type { RoundRecapAward } from "./RoundRecapAward";
import type { TeamStanding } from "./TeamStanding";

export type ShowLeaderboardData = { oldLeaderboard: Array<Player>, leaderboard: Array<Player>, teamStandings: Array<TeamStanding> | null, autoAdvanceMs: number | null, roundRecap: Array<RoundRecapAward> | null, };
