// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoundRecapAward } from "./RoundRecapAward";
import type { ScoringMode } from "./ScoringMode";

export type ShowResultData = { correct: boolean, message: string, points: number, myPoints: number, rank: number, aheadOfMe: string | null, streak?: number, streakBonus?: boolean, bonus?: boolean, firstCorrect?: boolean, poll?: boolean, achievements?: Array<string>, bonusPoints?: number, playerCount?: number, correctAnswer?: string, correctChunks?: Array<string>, autoAdvanceMs?: number, roundRecap?: Array<RoundRecapAward>, scoringMode?: ScoringMode, };
