// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuestionMedia } from "./QuestionMedia";

export type ShowQuestionData = { question: string, answers: Array<string> | null, displayOrder: Array<number> | null, media: QuestionMedia | null, cooldown: number, submittedBy: string | null, };
