// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchMode } from "./MatchMode";
import type { QuestionMedia } from "./QuestionMedia";
import type { RoundRecapAward } from "./RoundRecapAward";

export type ShowResponsesData = { question: string, responses: { [key in string]?: number }, solutions: Array<number>, answers: Array<string>, media: QuestionMedia | null, type: string | null, correct: number | null, unit: string | null, averageGuess: number | null, textResponses: { [key in string]?: number } | null, acceptedAnswers: Array<string> | null, matchMode: MatchMode | null, correctChunks: Array<string> | null, roundRecap: Array<RoundRecapAward> | null, };
