// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MatchMode } from "./MatchMode";
import type { QuestionMedia } from "./QuestionMedia";
import type { RoundRecapAward } from "./RoundRecapAward";

export type ShowResponsesData = { question: string, responses: { [key in string]?: number }, solutions: Array<number>, answers: Array<string>, media?: QuestionMedia, type?: string, correct?: number, unit?: string, cooldown: number, time: number, min?: number, max?: number, averageGuess?: number, textResponses?: { [key in string]?: number }, acceptedAnswers?: Array<string>, matchMode?: MatchMode, correctChunks?: Array<string>, roundRecap?: Array<RoundRecapAward>, };
