// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shared dropdown slot for fill-blank and matching (options + correct index).
 */
export type Slot = { options: Array<string>, correctIndex: number, };
