// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sound slot overrides. Each slot maps to a bundled default mp3 under /sounds/;
 * a theme may override a slot with a served asset ref. A null override means
 * playback falls back to the bundled default, so an absent/old theme.json stays
 * an audio no-op.
 *
 * Sent/received in: Theme.sounds
 */
export type SoundsConfig = { 
/**
 * Background music for answer selection phase
 */
answersMusic: string | null, 
/**
 * Sound effect when an answer is selected
 */
answersSound: string | null, 
/**
 * Sound for 3rd place podium finish
 */
podiumThree: string | null, 
/**
 * Sound for 2nd place podium finish
 */
podiumSecond: string | null, 
/**
 * Sound for 1st place podium finish
 */
podiumFirst: string | null, 
/**
 * Sound for podium snare roll (roll-up effect)
 */
podiumSnearRoll: string | null, 
/**
 * Sound effect at results screen entry
 */
results: string | null, 
/**
 * Sound effect for question reveal
 */
show: string | null, 
/**
 * Notification "boump" sound (e.g., player join)
 */
boump: string | null, 
/**
 * Sound for unlocking a Bronze-tier achievement
 */
tierBronze: string | null, 
/**
 * Sound for unlocking a Silver-tier achievement
 */
tierSilver: string | null, 
/**
 * Sound for unlocking a Gold-tier achievement
 */
tierGold: string | null, 
/**
 * Sound for unlocking a Diamant-tier achievement
 */
tierDiamant: string | null, };
