// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for manager:uploadSound and manager:soundUploaded events.
 * slot: one of the sound slot names (e.g., "answersMusic", "podiumFirst", etc.; SoundSlot).
 * dataUrl: base64-encoded audio data (on upload request).
 * assetRef: server-side asset reference (in success response).
 *
 * Sent/received in: manager:uploadSound, manager:soundUploaded
 */
export type SoundUploadPayload = { 
/**
 * Sound slot (e.g., "answersMusic", "podiumFirst", "tierGold")
 */
slot: string, 
/**
 * Base64-encoded audio data (on upload request only)
 */
dataUrl: string | null, 
/**
 * Server asset reference path (in success response only)
 */
assetRef: string | null, };
