// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Status = "SHOW_ROOM" | "SHOW_START" | "SHOW_PREPARED" | "SHOW_QUESTION" | "SELECT_ANSWER" | "SHOW_RESULT" | "SHOW_RESPONSES" | "SHOW_ROUND_RECAP" | "SHOW_LEADERBOARD" | "FINISHED" | "WAIT" | "PAUSED";
