// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Color palette for answer state feedback (correct/wrong).
 * Used to color answer buttons and feedback messages.
 *
 * Sent/received in: Theme.stateColors
 */
export type StateColors = { 
/**
 * Hex color for correct answers
 */
correct: string, 
/**
 * Hex color for wrong answers
 */
wrong: string, };
