// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * C2S: manager:submitUploadImage — Submit an uploaded image for storage.
 */
export type SubmitUploadImagePayload = { filename: string, dataUrl: string, };
