// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Submission category (public topic category).
 */
export type SubmissionCategory = "science" | "history" | "geography" | "general" | "sports" | "entertainment" | "technology" | "other";
