// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmissionStatus } from "./SubmissionStatus";

export type SubmissionMeta = { id: string, submittedBy: string, submittedAt: string, status: SubmissionStatus, question: string, };
