// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuperlativeKey } from "./SuperlativeKey";

/**
 * One awarded superlative from post-game recap.
 * Carries the winner's name, avatar (optional), and the numeric stat that won it.
 */
export type Superlative = { key: SuperlativeKey, winnerName: string, winnerAvatar?: string, value: number, };
