// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Superlative award key.
 * One of the post-game superlatives (fastest finger, most correct, etc.).
 */
export type SuperlativeKey = "fastest_finger" | "most_correct" | "most_wrong" | "longest_streak" | "biggest_climber" | "lucky_guesser" | "comeback_kid" | "most_achievements" | "hardest_question";
