// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * C2S payload for `player:flowerBattle:submitPowerupTargetVote`.
 *
 * `player_token` is **required** (SEC-01) — same gate as [`PowerupVotePayload`].
 */
export type TargetVotePayload = { gameId: string, targetTeamId: string, 
/**
 * Server-minted per-player secret from `game:successJoin` / localStorage.
 */
playerToken: string, };
