// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Color palette for team backgrounds (Red, Blue, Green, Yellow).
 * Used when a player selects a team during gameplay.
 *
 * Sent/received in: Theme.teamColors
 */
export type TeamColors = { 
/**
 * Hex color for the Red team
 */
red: string, 
/**
 * Hex color for the Blue team
 */
blue: string, 
/**
 * Hex color for the Green team
 */
green: string, 
/**
 * Hex color for the Yellow team
 */
yellow: string, };
