// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How players get a team in team-mode games (WP #952).
 * Wire values: `"self"` | `"auto"`. Missing / unknown → `SelfAssign`.
 */
export type TeamAssignment = "self" | "auto";
