// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

/**
 * A captured prior theme (WP-18 theme revision).
 * id is a timestamp-derived safe slug (e.g. `rev-${Date.now()}`);
 * createdAt is ISO timestamp. Used to enable undo/restore of theme changes.
 *
 * Sent/received in: themeRevision:data, themeRevision:restoreSuccess
 */
export type ThemeRevision = { 
/**
 * Unique identifier (timestamp-derived safe slug, e.g. "rev-1719946800000")
 */
id: string, 
/**
 * ISO 8601 timestamp when this revision was captured
 */
createdAt: string, 
/**
 * The full theme configuration at the time of capture
 */
theme: Theme, };
