// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

/**
 * A named, savable preset of a full Theme (stored one-per-file under
 * config/theme-templates/<id>.json). DATA on the wire carries the full template
 * so a picker can apply it without a second fetch.
 *
 * Sent/received in: themeTemplate:data
 */
export type ThemeTemplate = { 
/**
 * Unique identifier for the template (server-assigned slug of name)
 */
id: string, 
/**
 * Human-readable name of the template (max 60 chars)
 */
name: string, 
/**
 * The full theme configuration
 */
theme: Theme, };
