// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight listing of a template ({id, name}) — used by the design-tab picker
 * and carried in ManagerConfig.themeTemplates.
 */
export type ThemeTemplateMeta = { 
/**
 * Unique identifier for the template
 */
id: string, 
/**
 * Human-readable name of the template
 */
name: string, };
