// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimatedBackgroundsConfig } from "./AnimatedBackgroundsConfig";

/**
 * Background image and animation config for all three display slots.
 * - auth: Start/join/manager-login/result screens
 * - managerGame: Host's big presentation screen during a game
 * - playerGame: Player's in-game screen (phone)
 * - animatedCss: Generated CSS for the animated backdrop (readonly, server-computed)
 *
 * Sent/received in: Theme.backgrounds
 */
export type ThemeBackgrounds = { 
/**
 * Background image path for auth screens (null = none)
 */
auth: string | null, 
/**
 * Background image path for manager game screen (null = none)
 */
managerGame: string | null, 
/**
 * Background image path for player game screen (null = none)
 */
playerGame: string | null, 
/**
 * Animated background configs per slot
 */
animated: AnimatedBackgroundsConfig, 
/**
 * Generated CSS for the animated backdrop (readonly)
 */
animatedCss: string, };
