// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationConfig } from "./AnimationConfig";
import type { FooterColors } from "./FooterColors";
import type { RankColors } from "./RankColors";
import type { SoundsConfig } from "./SoundsConfig";
import type { StateColors } from "./StateColors";
import type { TeamColors } from "./TeamColors";
import type { ThemeBackgrounds } from "./ThemeBackgrounds";
import type { TierColors } from "./TierColors";

/**
 * The complete theme configuration for the application.
 * Persisted as config/theme.json and sent on manager:theme and game:status updates.
 * A single source of truth is the zod validator; a parsed/persisted theme IS a Theme.
 *
 * Sent/received in: manager:theme, manager:setTheme, manager:setThemeSuccess,
 * themeTemplate:data (via ThemeTemplate), themeRevision:data (via ThemeRevision),
 * themeRevision:restoreSuccess
 */
export type Theme = { 
/**
 * Visual style: "flat" or "glass"
 */
style: string, 
/**
 * Primary brand color (hex)
 */
colorPrimary: string, 
/**
 * Secondary brand color (hex)
 */
colorSecondary: string, 
/**
 * Text color (hex, default "#ffffff")
 */
colorText: string, 
/**
 * Array of 4 hex colors for the four answer slots (A, B, C, D)
 */
answerColors: [string, string, string, string], 
/**
 * Text color for answer buttons (hex, default "#0B0B12")
 */
answerTextColor: string, 
/**
 * Accent color for highlights/borders (hex, default "#ff9900")
 */
accentColor: string, 
/**
 * Border radius for cards/buttons (pixels, 0–40, default 16)
 */
radius: number, 
/**
 * Scrim opacity on images (0–100, default 0)
 */
scrim: number, 
/**
 * App title text (max 40 chars, can be null)
 */
appTitle?: string, 
/**
 * Logo asset reference (path under /theme/ or /media/, can be null)
 */
logo?: string, 
/**
 * Whether to show branding in the UI (default true)
 */
showBranding: boolean, 
/**
 * Background images and animation configs for all display slots
 */
backgrounds: ThemeBackgrounds, 
/**
 * Team colors (Red, Blue, Green, Yellow)
 */
teamColors: TeamColors, 
/**
 * Achievement tier colors (Bronze, Silver, Gold, Diamant)
 */
tierColors: TierColors, 
/**
 * Answer state colors (correct, wrong)
 */
stateColors: StateColors, 
/**
 * Rank change colors (up, down)
 */
rankColors: RankColors, 
/**
 * Hex color for timer urgency (when time is running out)
 */
timerUrgent: string, 
/**
 * Hex color for streak counter badges
 */
streakColor: string, 
/**
 * Hex color for muted surface elements
 */
surfaceMuted: string, 
/**
 * Footer colors (background, text)
 */
footerColors: FooterColors, 
/**
 * Spring-physics animation config
 */
animation: AnimationConfig, 
/**
 * Sound asset overrides per slot (null = use bundled default)
 */
sounds: SoundsConfig, 
/**
 * Whether custom CSS skeleton is enabled (default false)
 */
customCssEnabled: boolean, 
/**
 * Whether custom JS skeleton is enabled (default false)
 */
customJsEnabled: boolean, 
/**
 * Cache-bust version for skeleton CSS/JS (incremented on edit, default 0)
 */
skeletonVersion: number, };
