// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Color palette for achievement tier badges (Bronze, Silver, Gold, Diamant).
 * Used to visually distinguish achievement rarity.
 *
 * Sent/received in: Theme.tierColors
 */
export type TierColors = { 
/**
 * Hex color for Bronze-tier achievements
 */
bronze: string, 
/**
 * Hex color for Silver-tier achievements
 */
silver: string, 
/**
 * Hex color for Gold-tier achievements
 */
gold: string, 
/**
 * Hex color for Diamant-tier achievements
 */
diamant: string, };
