// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TokenPos: per-token POS assignment (wortarten reveal)
 */
export type TokenPos = { token: string, pos: string, };
