/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as DisplayLayoutRouteImport } from './pages/display/layout'
import { Route as authLayoutRouteImport } from './pages/(auth)/layout'
import { Route as TrophiesIndexRouteImport } from './pages/trophies/index'
import { Route as SubmitIndexRouteImport } from './pages/submit/index'
import { Route as DisplayIndexRouteImport } from './pages/display/index'
import { Route as authIndexRouteImport } from './pages/(auth)/index'
import { Route as SatelliteGameIdRouteImport } from './pages/satellite/$gameId'
import { Route as RIdRouteImport } from './pages/r/$id'
import { Route as PartyGameIdRouteImport } from './pages/party/$gameId'
import { Route as ManagerConfigRouteImport } from './pages/manager/config'
import { Route as DisplayPlayRouteImport } from './pages/display/play'
import { Route as ManagerQuizzLayoutRouteImport } from './pages/manager/quizz/layout'
import { Route as ManagerQuizzIndexRouteImport } from './pages/manager/quizz/index'
import { Route as authManagerIndexRouteImport } from './pages/(auth)/manager/index'
import { Route as QuizzIdSoloRouteImport } from './pages/quizz/$id/solo'
import { Route as PartyManagerGameIdRouteImport } from './pages/party/manager/$gameId'
import { Route as ManagerQuizzQuizzIdRouteImport } from './pages/manager/quizz/$quizzId'

const DisplayLayoutRoute = DisplayLayoutRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const TrophiesIndexRoute = TrophiesIndexRouteImport.update({
  id: '/trophies/',
  path: '/trophies/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitIndexRoute = SubmitIndexRouteImport.update({
  id: '/submit/',
  path: '/submit/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayIndexRoute = DisplayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DisplayLayoutRoute,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLayoutRoute,
} as any)
const SatelliteGameIdRoute = SatelliteGameIdRouteImport.update({
  id: '/satellite/$gameId',
  path: '/satellite/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyGameIdRoute = PartyGameIdRouteImport.update({
  id: '/party/$gameId',
  path: '/party/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerConfigRoute = ManagerConfigRouteImport.update({
  id: '/manager/config',
  path: '/manager/config',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayPlayRoute = DisplayPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => DisplayLayoutRoute,
} as any)
const ManagerQuizzLayoutRoute = ManagerQuizzLayoutRouteImport.update({
  id: '/manager/quizz',
  path: '/manager/quizz',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerQuizzIndexRoute = ManagerQuizzIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerQuizzLayoutRoute,
} as any)
const authManagerIndexRoute = authManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => authLayoutRoute,
} as any)
const QuizzIdSoloRoute = QuizzIdSoloRouteImport.update({
  id: '/quizz/$id/solo',
  path: '/quizz/$id/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyManagerGameIdRoute = PartyManagerGameIdRouteImport.update({
  id: '/party/manager/$gameId',
  path: '/party/manager/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerQuizzQuizzIdRoute = ManagerQuizzQuizzIdRouteImport.update({
  id: '/$quizzId',
  path: '/$quizzId',
  getParentRoute: () => ManagerQuizzLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/display': typeof DisplayLayoutRouteWithChildren
  '/manager/quizz': typeof ManagerQuizzLayoutRouteWithChildren
  '/display/play': typeof DisplayPlayRoute
  '/manager/config': typeof ManagerConfigRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/r/$id': typeof RIdRoute
  '/satellite/$gameId': typeof SatelliteGameIdRoute
  '/': typeof authIndexRoute
  '/display/': typeof DisplayIndexRoute
  '/submit/': typeof SubmitIndexRoute
  '/trophies/': typeof TrophiesIndexRoute
  '/manager/quizz/$quizzId': typeof ManagerQuizzQuizzIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/quizz/$id/solo': typeof QuizzIdSoloRoute
  '/manager/': typeof authManagerIndexRoute
  '/manager/quizz/': typeof ManagerQuizzIndexRoute
}
export interface FileRoutesByTo {
  '/display/play': typeof DisplayPlayRoute
  '/manager/config': typeof ManagerConfigRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/r/$id': typeof RIdRoute
  '/satellite/$gameId': typeof SatelliteGameIdRoute
  '/': typeof authIndexRoute
  '/display': typeof DisplayIndexRoute
  '/submit': typeof SubmitIndexRoute
  '/trophies': typeof TrophiesIndexRoute
  '/manager/quizz/$quizzId': typeof ManagerQuizzQuizzIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/quizz/$id/solo': typeof QuizzIdSoloRoute
  '/manager': typeof authManagerIndexRoute
  '/manager/quizz': typeof ManagerQuizzIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/display': typeof DisplayLayoutRouteWithChildren
  '/manager/quizz': typeof ManagerQuizzLayoutRouteWithChildren
  '/display/play': typeof DisplayPlayRoute
  '/manager/config': typeof ManagerConfigRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/r/$id': typeof RIdRoute
  '/satellite/$gameId': typeof SatelliteGameIdRoute
  '/(auth)/': typeof authIndexRoute
  '/display/': typeof DisplayIndexRoute
  '/submit/': typeof SubmitIndexRoute
  '/trophies/': typeof TrophiesIndexRoute
  '/manager/quizz/$quizzId': typeof ManagerQuizzQuizzIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/quizz/$id/solo': typeof QuizzIdSoloRoute
  '/(auth)/manager/': typeof authManagerIndexRoute
  '/manager/quizz/': typeof ManagerQuizzIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/display'
    | '/manager/quizz'
    | '/display/play'
    | '/manager/config'
    | '/party/$gameId'
    | '/r/$id'
    | '/satellite/$gameId'
    | '/'
    | '/display/'
    | '/submit/'
    | '/trophies/'
    | '/manager/quizz/$quizzId'
    | '/party/manager/$gameId'
    | '/quizz/$id/solo'
    | '/manager/'
    | '/manager/quizz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/display/play'
    | '/manager/config'
    | '/party/$gameId'
    | '/r/$id'
    | '/satellite/$gameId'
    | '/'
    | '/display'
    | '/submit'
    | '/trophies'
    | '/manager/quizz/$quizzId'
    | '/party/manager/$gameId'
    | '/quizz/$id/solo'
    | '/manager'
    | '/manager/quizz'
  id:
    | '__root__'
    | '/(auth)'
    | '/display'
    | '/manager/quizz'
    | '/display/play'
    | '/manager/config'
    | '/party/$gameId'
    | '/r/$id'
    | '/satellite/$gameId'
    | '/(auth)/'
    | '/display/'
    | '/submit/'
    | '/trophies/'
    | '/manager/quizz/$quizzId'
    | '/party/manager/$gameId'
    | '/quizz/$id/solo'
    | '/(auth)/manager/'
    | '/manager/quizz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  DisplayLayoutRoute: typeof DisplayLayoutRouteWithChildren
  ManagerQuizzLayoutRoute: typeof ManagerQuizzLayoutRouteWithChildren
  ManagerConfigRoute: typeof ManagerConfigRoute
  PartyGameIdRoute: typeof PartyGameIdRoute
  RIdRoute: typeof RIdRoute
  SatelliteGameIdRoute: typeof SatelliteGameIdRoute
  SubmitIndexRoute: typeof SubmitIndexRoute
  TrophiesIndexRoute: typeof TrophiesIndexRoute
  PartyManagerGameIdRoute: typeof PartyManagerGameIdRoute
  QuizzIdSoloRoute: typeof QuizzIdSoloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trophies/': {
      id: '/trophies/'
      path: '/trophies'
      fullPath: '/trophies/'
      preLoaderRoute: typeof TrophiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit/': {
      id: '/submit/'
      path: '/submit'
      fullPath: '/submit/'
      preLoaderRoute: typeof SubmitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/': {
      id: '/display/'
      path: '/'
      fullPath: '/display/'
      preLoaderRoute: typeof DisplayIndexRouteImport
      parentRoute: typeof DisplayLayoutRoute
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/satellite/$gameId': {
      id: '/satellite/$gameId'
      path: '/satellite/$gameId'
      fullPath: '/satellite/$gameId'
      preLoaderRoute: typeof SatelliteGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/$gameId': {
      id: '/party/$gameId'
      path: '/party/$gameId'
      fullPath: '/party/$gameId'
      preLoaderRoute: typeof PartyGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/config': {
      id: '/manager/config'
      path: '/manager/config'
      fullPath: '/manager/config'
      preLoaderRoute: typeof ManagerConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/play': {
      id: '/display/play'
      path: '/play'
      fullPath: '/display/play'
      preLoaderRoute: typeof DisplayPlayRouteImport
      parentRoute: typeof DisplayLayoutRoute
    }
    '/manager/quizz': {
      id: '/manager/quizz'
      path: '/manager/quizz'
      fullPath: '/manager/quizz'
      preLoaderRoute: typeof ManagerQuizzLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/quizz/': {
      id: '/manager/quizz/'
      path: '/'
      fullPath: '/manager/quizz/'
      preLoaderRoute: typeof ManagerQuizzIndexRouteImport
      parentRoute: typeof ManagerQuizzLayoutRoute
    }
    '/(auth)/manager/': {
      id: '/(auth)/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof authManagerIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/quizz/$id/solo': {
      id: '/quizz/$id/solo'
      path: '/quizz/$id/solo'
      fullPath: '/quizz/$id/solo'
      preLoaderRoute: typeof QuizzIdSoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/manager/$gameId': {
      id: '/party/manager/$gameId'
      path: '/party/manager/$gameId'
      fullPath: '/party/manager/$gameId'
      preLoaderRoute: typeof PartyManagerGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/quizz/$quizzId': {
      id: '/manager/quizz/$quizzId'
      path: '/$quizzId'
      fullPath: '/manager/quizz/$quizzId'
      preLoaderRoute: typeof ManagerQuizzQuizzIdRouteImport
      parentRoute: typeof ManagerQuizzLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authIndexRoute: typeof authIndexRoute
  authManagerIndexRoute: typeof authManagerIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authIndexRoute: authIndexRoute,
  authManagerIndexRoute: authManagerIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface DisplayLayoutRouteChildren {
  DisplayPlayRoute: typeof DisplayPlayRoute
  DisplayIndexRoute: typeof DisplayIndexRoute
}

const DisplayLayoutRouteChildren: DisplayLayoutRouteChildren = {
  DisplayPlayRoute: DisplayPlayRoute,
  DisplayIndexRoute: DisplayIndexRoute,
}

const DisplayLayoutRouteWithChildren = DisplayLayoutRoute._addFileChildren(
  DisplayLayoutRouteChildren,
)

interface ManagerQuizzLayoutRouteChildren {
  ManagerQuizzQuizzIdRoute: typeof ManagerQuizzQuizzIdRoute
  ManagerQuizzIndexRoute: typeof ManagerQuizzIndexRoute
}

const ManagerQuizzLayoutRouteChildren: ManagerQuizzLayoutRouteChildren = {
  ManagerQuizzQuizzIdRoute: ManagerQuizzQuizzIdRoute,
  ManagerQuizzIndexRoute: ManagerQuizzIndexRoute,
}

const ManagerQuizzLayoutRouteWithChildren =
  ManagerQuizzLayoutRoute._addFileChildren(ManagerQuizzLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  DisplayLayoutRoute: DisplayLayoutRouteWithChildren,
  ManagerQuizzLayoutRoute: ManagerQuizzLayoutRouteWithChildren,
  ManagerConfigRoute: ManagerConfigRoute,
  PartyGameIdRoute: PartyGameIdRoute,
  RIdRoute: RIdRoute,
  SatelliteGameIdRoute: SatelliteGameIdRoute,
  SubmitIndexRoute: SubmitIndexRoute,
  TrophiesIndexRoute: TrophiesIndexRoute,
  PartyManagerGameIdRoute: PartyManagerGameIdRoute,
  QuizzIdSoloRoute: QuizzIdSoloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
