import StyleDictionary from 'style-dictionary'
import { execSync } from 'child_process'

const toKebab = (str) =>
  str
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[\s_.]+/g, '-')
    .toLowerCase()

const sd = new StyleDictionary({
  source: ['design.tokens.json'],
  platforms: {
    typescript: {
      transformGroup: 'js',
      buildPath: 'packages/common/src/',
      files: [
        {
          destination: 'theme-tokens.generated.ts',
          format: 'typescript/tokens'
        }
      ]
    },
    css: {
      transformGroup: 'css',
      buildPath: 'build/css/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: {
            outputReferences: true
          }
        }
      ]
    }
  }
})

sd.registerFormat({
  name: 'typescript/tokens',
  format: ({ dictionary }) => {
    const tokens = dictionary.allTokens
    const tokenNames = Array.from(
      new Set(tokens.map((t) => `--${toKebab(t.name)}`))
    )
    const typeUnion = tokenNames.map((name) => `  | "${name}"`).join('\n')

    return `/**
 * Auto-generated by Style Dictionary from design.tokens.json.
 * DO NOT EDIT DIRECTLY.
 */

export type CssTokenName =
${typeUnion}

/**
 * Returns a CSS \`var(...)\` expression for a design token name in a type-safe way.
 */
export function getThemeTokenCssVar(token: CssTokenName): string {
  return \`var(\${token})\`
}
`
  }
})

await sd.buildAllPlatforms()

// Auto-generate Living Design System documentation table
execSync('node scripts/generate-tokens-doc.mjs', { stdio: 'inherit' })
